apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-blue
  namespace: blue-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: blue
  template:
    metadata:
      labels:
        app: myapp
        version: blue #V1
    spec:
      containers:
      - name: app
        image: app-blue:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
