apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-green
  namespace: blue-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: green
  template:
    metadata:
      labels:
        app: myapp
        version: green #v2
    spec:
      containers:
      - name: app
        image: app-green:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
