apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: belo
spec:
  selector:
    version: blue # Cambiar a "green" para cambiar de versión
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
