apiVersion: v1
kind: Service
metadata:
  name: blue-green-service
  namespace: blue-green
spec:
  selector:
    version: blue # Cambiar a "green" para cambiar de versión
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
